#!/bin/bash
set -euo pipefail

SCRIPT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd -P )"

mkdir -p "$SCRIPT_ROOT/devices"

set -x
rm -f "$SCRIPT_ROOT/devices/*.yaml"
ssh "$HA_HOST" 'bash -xc "cd /homeassistant/esphome/; tar -zc *.yaml fonts"' | tar -zvx -C "$SCRIPT_ROOT/devices"
