esphome:
  name: ir2
  friendly_name: ir2
esp8266:
  board: esp8285
api:
  encryption:
    key: !secret ir2__encryption_key
ota:
  platform: esphome
  password: !secret ir2__ota_password
wifi:
  ssid: !secret niot_ssid
  password: !secret niot_password
  use_address: 10.32.5.86
logger:
web_server:
mdns:

switch:
  - platform: restart
    name: "Restart"
remote_receiver:
  id: rcvr
  pin:
    number: GPIO14
    inverted: true
  dump: all
remote_transmitter:
  id: tmtr
  pin: GPIO4
  carrier_duty_percent: 50%
climate:
  - platform: fujitsu_general
    name: AC
    receiver_id: rcvr
    transmitter_id: tmtr
    # sensor: current_temperature
    visual:
      min_temperature: 16
      max_temperature: 25
      temperature_step:
        target_temperature: 1
        current_temperature: 0.1
# sensor:
#   - platform: homeassistant
#     id: current_temperature
#     entity_id: sensor.ikea_of_sweden_vindstyrka_temperature  # dining room IKEA
#     internal: True
