esphome:
  name: plug8
  friendly_name: plug8

# Sonoff TH Origin THR316 with THS01 temperature/humidity probe
esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret plug8__encryption_key

ota:
  - platform: esphome
    password: !secret plug8__ota_password

wifi:
  ssid: !secret niot_ssid
  password: !secret niot_password
  use_address: 10.32.5.118
  # ssid: !secret wifi_ssid
  # password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Plug8 Fallback Hotspot"
    password: !secret plug8__ap_password

captive_portal:
web_server:
mdns:

binary_sensor:
  - platform: gpio
    name: "Button"
    internal: true
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - light.toggle: light_relay
  - platform: status
    name: "Status"

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
  - platform: internal_temperature
    name: "Internal ESP32 Temp"
  - platform: dht
    model: SI7021
    pin: GPIO25
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    update_interval: 60s

output:
  - platform: gpio
    id: relay
    pin: GPIO21

light:
  - platform: binary
    id: light_relay
    name: "Light"
    output: relay
    restore_mode: RESTORE_DEFAULT_OFF

switch:
  # 3.3V supply for the sensor jack
  - platform: gpio
    id: sensor_power
    internal: true
    pin: GPIO27
    restore_mode: ALWAYS_ON
  - platform: restart
    name: "Restart"

status_led:
  pin:
    number: GPIO15
    inverted: True
